export const GET_SCHOLARSHIPS = 'GET_SCHOLARSHIPS';
export const SCHOLARSHIPS_LOADING = 'SCHOLARSHIPS_LOADING';

export const CREATE_SCHOLARSHIP = 'CREATE_SCHOLARSHIP';
export const CREATE_SCHOLARSHIP_SUCCESS = 'CREATE_SCHOLARSHIP_SUCCESS';
export const CREATE_SCHOLARSHIP_FAIL = 'CREATE_SCHOLARSHIP_FAIL';

export const UPDATE_SCHOLARSHIP = 'UPDATE_SCHOLARSHIP';
export const UPDATE_SCHOLARSHIP_FAIL = 'UPDATE_SCHOLARSHIP_FAIL';

export const DELETE_SCHOLARSHIP = 'DELETE_SCHOLARSHIP';
export const DELETE_SCHOLARSHIP_FAIL = 'DELETE_SCHOLARSHIP_FAIL';
